name: python-weather1
on: 
  push:
    branches:
      - master
  schedule:
    - cron: '0/5 * * * *'
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
    - name: install
      run: |
        echo '''${{ secrets.FIREBASEKEY }}''' > firebasekey.json
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: python main
      run: |
        python3 main.py
